apiVersion: v1
kind: Service
metadata:
  name: fluentd-aggregator-service
  namespace: logging
  labels:
    k8s-app: fluentd-aggregator
spec:
  type: ClusterIP
  selector:
    k8s-app: fluentd-aggregator
  ports:
  # - name: fluentd-input
  #   port: 24224
  #   targetPort: fwd-input
  #   protocol: TCP
  # - name: fluentd-input-udp
  #   port: 24224
  #   targetPort: fwd-input-udp
  #   protocol: UDP
  # # Exposes Prometheus metrics
  # - name: prometheus-metrics
  #   port: 24231
  #   targetPort: prom-metrics
  #   protocol: TCP
  # # Can be accessed using "kubectl proxy" at:
  # # http://127.0.0.1:8001/api/v1/proxy/namespaces/kube-system/services/fluentd-aggregator:monitor-agent/api/plugins.json
  # - name: monitor-agent
  #   port: 24220
  #   targetPort: monitor-agent
  #   protocol: TCP
    - port: 24224
      targetPort: 24224
      protocol: TCP
      name: fluentd
    - port: 9880
      targetPort: 9880
      protocol: TCP
      name: http
    - port: 5140
      targetPort: 5140
      protocol: UDP
      name: syslog
    - port: 12201
      targetPort: 12201
      protocol: UDP
      name: graylog
