apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-aggregator
  namespace: logging
  labels:
    k8s-app: fluentd-aggregator
    component: log-aggregator
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-aggregator
      component: log-aggregator
  template:
    metadata:
      labels:
        k8s-app: fluentd-aggregator
        component: log-aggregator
    spec:
      containers:
      - name: fluentd-aggregator
        image: localhost:5000/fluent/fluentd-kubernetes:1.2
        imagePullPolicy: Always
        command: ["fluentd", "-c", "/fluentd/etc/fluentd.conf", "-p", "/fluentd/plugins"]
        ports:
          - containerPort: 5140
            protocol: UDP
            name: syslog
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: fluentd-config
            mountPath: /fluentd/etc/fluentd.conf
            subPath: fluentd.conf
          - name: fluentd-config
            mountPath: /fluentd/etc/conf/kubernetes.conf
            subPath: kubernetes.conf
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluentd-config
          configMap:
            name: fluentd-config
      serviceAccount: fluentd-service-account
      serviceAccountName: fluentd-service-account
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
