apiVersion: v1
kind: Service
metadata:
  name: web-server-service
  namespace: web
  labels:
    k8s-app: web-server
spec:
  type: NodePort
  selector:
    k8s-app: web-server
  ports:
    - name: web-server
      port: 80
      protocol: TCP
      targetPort: web-server
      nodePort: 30002
