apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: web
  labels:
    k8s-app: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: web-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: web-server
    spec:
      containers:
        - name: web-server
          image: nginx:1.16-alpine
          imagePullPolicy: Always
          ports:
            - name: web-server
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/web.conf
              subPath: web.conf
            - name: nginx-config
              mountPath: /var/www/public/index.html
              subPath: index.html
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
      restartPolicy: Always
